apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  commonName: root-ca
  secretName: root-ca
  duration: 2160h
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca
spec:
  ca:
    secretName: root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca-intermediate
  namespace: istio-system
spec:
  commonName: istio-ca-intermediate
  secretName: istio-ca-intermediate
  duration: 2160h
  isCA: true
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-int-ca
  namespace: linkerd
spec:
  commonName: linkerd-int-ca
  secretName: service-mesh-ca
  duration: 2160h
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  duration: 2160h
  secretName: linkerd-identity-issuer
  issuerRef:
    name: service-mesh-ca
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: osm-ca-intermediate
  namespace: osm-system
spec:
  isCA: true
  duration: 2160h
  secretName: osm-ca-intermediate
  commonName: osm-system
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
    group: cert-manager.io
