apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  commonName: root-ca
  secretName: root-ca
  duration: 2160h
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca
spec:
  ca:
    secretName: root-ca
---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: linkerd-ca-intermediate
#  namespace: linkerd
#spec:
#  commonName: linkerd-ca-intermediate
#  secretName: linkerd-ca-intermediate
#  duration: 2160h
#  isCA: true
#  issuerRef:
#    name: root-ca
#    kind: ClusterIssuer
#---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: linkerd-intermediate-ca
#  namespace: linkerd
#spec:
#  ca:
#    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-ca-intermediate
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: linkerd-int-ca
#  namespace: linkerd
#spec:
#  commonName: linkerd-int-ca
#  secretName: service-mesh-ca
#  duration: 2160h
#  isCA: true
#  issuerRef:
#    name: selfsigned
#    kind: ClusterIssuer
---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: linkerd-identity-issuer
#  namespace: linkerd
#spec:
#  secretName: linkerd-identity-issuer
#  issuerRef:
#    name: service-mesh-ca
#    kind: ClusterIssuer
#  commonName: identity.linkerd.cluster.local
#  dnsNames:
#  - identity.linkerd.cluster.local
#  isCA: true
#  privateKey:
#    algorithm: ECDSA
#  usages:
#  - cert sign
#  - crl sign
#  - server auth
#  - client auth
